
name: hello-world

on:
  push:
  workflow_dispatch:
  
 #schedule:
    #- cron: "0 * * * *"     # Every hour at minute 0 (UTC)
    #- cron: "30 2 * * *"    # Every day at 02:30 UTC

  #workflow_dispatch:

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo text
        run: |
          echo "Hello, world!"
          date -u
