
name: hello-world

on:
  push:
  workflow_dispatch:
  
 #schedule:
    #- cron: "0 * * * *"     # Every hour at minute 0 (UTC)
    #- cron: "30 2 * * *"    # Every day at 02:30 UTC

  #workflow_dispatch:

jobs:

  hello-job1:
    runs-on: ubuntu-latest
    steps:
      - name: 
        run: sleep 600
      - name: Echo text
        run: |
          echo "Hello, world! Job 2"
          date -u
        timeout-minutes: 2

  hello-job2:
    runs-on: ubuntu-latest
    steps:
      - name: Echo text
        run: |
          echo "Hello, world! Job 2"
          date -u

  hello-job3:
    runs-on: ubuntu-latest
    steps:
      - name: Echo text
        run: |
          echo "Hello, world! Job 2"
          date -u
