#comment out
name: hello-world

on:
  push:
    branches:
      - main
      - prod2
  workflow_dispatch:
  # If you want the schedules back, just uncomment:
  # schedule:
  #   - cron: "0 * * * *"     # Every hour (UTC)
  #   - cron: "30 2 * * *"    # Daily at 02:30 UTC

jobs:
  phase_1:
    runs-on: ubuntu-latest
   
    steps:
      - name: Echo text 
        run: |
          echo "Hello World"
          date -u
